zuul:
  routes:
    shop-app:
      path: /**
      serviceId: shop-app-service
      sensitiveHeaders:
    admin-tool:
      path: /admin/**
      serviceId: admin-tool-service
      sensitiveHeaders:

#shop-app-service:
#  ribbon:
#    listOfServers: http://localhost:8081,http://localhost:8082
#
#admin-tool-service:
#  ribbon:
#    listOfServers: http://localhost:8087,http://localhost:8088

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true